"""
Description: This file contains the constants used in the project.
"""

# Grid values
BLOCKS_VALUE = 0
VERTICAL_ROAD_VALUE_LEFT = 1
VERTICAL_ROAD_VALUE_RIGHT = 2
HORIZONTAL_ROAD_VALUE_LEFT = 3
HORIZONTAL_ROAD_VALUE_RIGHT = 4

# Intersection values
INTERSECTION_DRIVE = 5
INTERSECTION_EXIT = 6

# Car values
CAR_HEAD = 7
CAR_BODY = 10

# Car directions
CAR_DIRECTION = {
    1: "⬇️",
    2: "⬆️",
    3: "⬅️",
    4: "➡️",
}

# Rotary flags
FIXED_DESTINATION = 0
FREE_MOVEMENT = 1

# SLIDER VALUES
MIN_SPEED = 1
MAX_SPEED = 5

# TRAFFIC JAM
TRAFFIC_JAM = 1

# File type
FILE_EXTENSION = "txt"

# Density tracking constants
ROAD_CELLS = [
    VERTICAL_ROAD_VALUE_LEFT,
    VERTICAL_ROAD_VALUE_RIGHT,
    HORIZONTAL_ROAD_VALUE_LEFT,
    HORIZONTAL_ROAD_VALUE_RIGHT,
]
INTERSECTION_CELLS = [INTERSECTION_DRIVE, INTERSECTION_EXIT]
