BLOCKS_VALUE = 0
VERTICAL_ROAD_VALUE_LEFT = 1
VERTICAL_ROAD_VALUE_RIGHT = 2
HORIZONTAL_ROAD_VALUE_LEFT = 3
HORIZONTAL_ROAD_VALUE_RIGHT = 4
INTERSECTION_INTERNAL = 5
INTERSECTION_EXIT = 6
CAR_HEAD = 7
CAR_BODY = 8
FILE_EXTENSION = "txt"

# Density tracking constants
ROAD_CELLS = [
    VERTICAL_ROAD_VALUE_LEFT,
    VERTICAL_ROAD_VALUE_RIGHT,
    HORIZONTAL_ROAD_VALUE_LEFT,
    HORIZONTAL_ROAD_VALUE_RIGHT,
]
INTERSECTION_CELLS = [INTERSECTION_INTERNAL, INTERSECTION_EXIT]
